/**
 * Auto-generated Supabase database types.
 *
 * Regenerate after any schema change:
 *   npx supabase gen types typescript --local > types/database.ts
 *
 * DO NOT edit this file by hand.
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      organizations: {
        Row: {
          id: string;
          name: string;
          slug: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["organizations"]["Insert"]>;
        Relationships: [];
      };

      profiles: {
        Row: {
          id: string;
          full_name: string | null;
          avatar_url: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          full_name?: string | null;
          avatar_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["profiles"]["Insert"]>;
        Relationships: [];
      };

      organization_memberships: {
        Row: {
          id: string;
          organization_id: string;
          user_id: string;
          role: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          user_id: string;
          role?: string;
          created_at?: string;
        };
        Update: Partial<
          Database["public"]["Tables"]["organization_memberships"]["Insert"]
        >;
        Relationships: [];
      };

      icp_profiles: {
        Row: {
          id: string;
          organization_id: string;
          name: string;
          description: string | null;
          criteria: Json;
          apollo_filters: Json | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          name: string;
          description?: string | null;
          criteria?: Json;
          apollo_filters?: Json | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["icp_profiles"]["Insert"]>;
        Relationships: [];
      };

      leads: {
        Row: {
          id: string;
          organization_id: string;
          // Canonical plan columns
          first_name: string | null;
          last_name: string | null;
          email: string | null;
          company: string | null;
          title: string | null;
          linkedin_url: string | null;
          enrichment_data: Json | null;
          enriched_at: string | null;
          hubspot_contact_id: string | null;
          source: string | null;
          // Legacy columns — remove in P1 cleanup
          name: string | null;
          stage: string | null;
          icp_id: string | null;
          icp_fit: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          first_name?: string | null;
          last_name?: string | null;
          email?: string | null;
          company?: string | null;
          title?: string | null;
          linkedin_url?: string | null;
          enrichment_data?: Json | null;
          enriched_at?: string | null;
          hubspot_contact_id?: string | null;
          source?: string | null;
          name?: string | null;
          stage?: string | null;
          icp_id?: string | null;
          icp_fit?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["leads"]["Insert"]>;
        Relationships: [];
      };

      lead_lists: {
        Row: {
          id: string;
          organization_id: string;
          name: string;
          description: string | null;
          filters: Json | null;
          lead_count: number;
          created_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          name: string;
          description?: string | null;
          filters?: Json | null;
          lead_count?: number;
          created_by?: string | null;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["lead_lists"]["Insert"]>;
        Relationships: [];
      };

      lead_list_members: {
        Row: {
          lead_list_id: string;
          lead_id: string;
          added_at: string;
        };
        Insert: {
          lead_list_id: string;
          lead_id: string;
          added_at?: string;
        };
        Update: Partial<
          Database["public"]["Tables"]["lead_list_members"]["Insert"]
        >;
        Relationships: [];
      };

      campaigns: {
        Row: {
          id: string;
          organization_id: string;
          name: string;
          status: string;
          instantly_campaign_id: string | null;
          lead_list_id: string | null;
          settings: Json | null;
          emails_sent: number;
          emails_opened: number;
          emails_replied: number;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          name: string;
          status?: string;
          instantly_campaign_id?: string | null;
          lead_list_id?: string | null;
          settings?: Json | null;
          emails_sent?: number;
          emails_opened?: number;
          emails_replied?: number;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["campaigns"]["Insert"]>;
        Relationships: [];
      };

      conversations: {
        Row: {
          id: string;
          organization_id: string;
          lead_id: string | null;
          campaign_id: string | null;
          agent_type: string | null;
          title: string | null;
          status: string;
          // Legacy columns — remove in P1 cleanup
          icp_id: string | null;
          token_cost_input: number;
          token_cost_output: number;
          blob_url: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          lead_id?: string | null;
          campaign_id?: string | null;
          agent_type?: string | null;
          title?: string | null;
          status?: string;
          icp_id?: string | null;
          token_cost_input?: number;
          token_cost_output?: number;
          blob_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<
          Database["public"]["Tables"]["conversations"]["Insert"]
        >;
        Relationships: [];
      };

      messages: {
        Row: {
          id: string;
          conversation_id: string;
          organization_id: string;
          role: string;
          content: string | null;
          metadata: Json | null;
          // Legacy columns — remove in P1 cleanup
          tool_call_id: string | null;
          artifact_type: string | null;
          artifact_data: Json | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          conversation_id: string;
          organization_id: string;
          role: string;
          content?: string | null;
          metadata?: Json | null;
          tool_call_id?: string | null;
          artifact_type?: string | null;
          artifact_data?: Json | null;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["messages"]["Insert"]>;
        Relationships: [];
      };

      agent_runs: {
        Row: {
          id: string;
          organization_id: string;
          conversation_id: string | null;
          pipeline_job_id: string | null;
          status: string;
          started_at: string | null;
          completed_at: string | null;
          // Canonical plan columns
          error: string | null;
          result: Json | null;
          // Legacy columns — remove in P1 cleanup
          agent_type: string | null;
          input_payload: Json | null;
          output_payload: Json | null;
          error_message: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          conversation_id?: string | null;
          pipeline_job_id?: string | null;
          status?: string;
          started_at?: string | null;
          completed_at?: string | null;
          error?: string | null;
          result?: Json | null;
          agent_type?: string | null;
          input_payload?: Json | null;
          output_payload?: Json | null;
          error_message?: string | null;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["agent_runs"]["Insert"]>;
        Relationships: [];
      };

      integration_accounts: {
        Row: {
          id: string;
          organization_id: string;
          provider: string;
          status: string;
          metadata: Json | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          provider: string;
          status?: string;
          metadata?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<
          Database["public"]["Tables"]["integration_accounts"]["Insert"]
        >;
        Relationships: [];
      };

      sync_runs: {
        Row: {
          id: string;
          organization_id: string;
          integration_account_id: string | null;
          job_type: string;
          status: string;
          synced_count: number;
          error: string | null;
          started_at: string | null;
          completed_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          integration_account_id?: string | null;
          job_type: string;
          status?: string;
          synced_count?: number;
          error?: string | null;
          started_at?: string | null;
          completed_at?: string | null;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["sync_runs"]["Insert"]>;
        Relationships: [];
      };

      pipeline_jobs: {
        Row: {
          id: string;
          organization_id: string;
          created_by: string | null;
          job_type: string;
          status: string;
          priority: number;
          payload: Json;
          scheduled_at: string;
          attempt_count: number;
          lease_expires_at: string | null;
          worker_id: string | null;
          result_artifact_id: string | null;
          last_error: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          created_by?: string | null;
          job_type: string;
          status?: string;
          priority?: number;
          payload?: Json;
          scheduled_at?: string;
          attempt_count?: number;
          lease_expires_at?: string | null;
          worker_id?: string | null;
          result_artifact_id?: string | null;
          last_error?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<
          Database["public"]["Tables"]["pipeline_jobs"]["Insert"]
        >;
        Relationships: [];
      };

      pipeline_job_attempts: {
        Row: {
          id: string;
          job_id: string;
          attempt_number: number;
          worker_id: string | null;
          started_at: string | null;
          completed_at: string | null;
          outcome: string | null;
          error_summary: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          job_id: string;
          attempt_number: number;
          worker_id?: string | null;
          started_at?: string | null;
          completed_at?: string | null;
          outcome?: string | null;
          error_summary?: string | null;
          created_at?: string;
        };
        Update: Partial<
          Database["public"]["Tables"]["pipeline_job_attempts"]["Insert"]
        >;
        Relationships: [];
      };

      artifacts: {
        Row: {
          id: string;
          organization_id: string;
          job_id: string | null;
          artifact_type: string;
          storage_path: string;
          mime_type: string | null;
          size_bytes: number | null;
          metadata: Json | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          job_id?: string | null;
          artifact_type: string;
          storage_path: string;
          mime_type?: string | null;
          size_bytes?: number | null;
          metadata?: Json | null;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["artifacts"]["Insert"]>;
        Relationships: [];
      };

      webhook_events: {
        Row: {
          id: string;
          organization_id: string | null;
          provider: string;
          event_type: string | null;
          provider_event_id: string | null;
          raw_payload: Json;
          processing_status: string;
          pipeline_job_id: string | null;
          received_at: string;
          processed_at: string | null;
        };
        Insert: {
          id?: string;
          organization_id?: string | null;
          provider: string;
          event_type?: string | null;
          provider_event_id?: string | null;
          raw_payload: Json;
          processing_status?: string;
          pipeline_job_id?: string | null;
          received_at?: string;
          processed_at?: string | null;
        };
        Update: Partial<
          Database["public"]["Tables"]["webhook_events"]["Insert"]
        >;
        Relationships: [];
      };
    };

    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
}
